name: 522_lab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.3.3
  - matplotlib=3.10.8
  - scikit-learn=1.7.2
  - altair=6.0.0
  - pandera=0.27.0
  - ipykernel=7.1.0
  - pip=24.2
  - pip:
      - deepchecks==0.19.1

